import { strFromU8, unzipSync } from 'fflate';

export const STATUS = {
  OK_IMPORTAR: 'OK_IMPORTAR',
  PENDENTE_MATRICULA_NAO_ENCONTRADA: 'PENDENTE_MATRICULA_NAO_ENCONTRADA',
  PENDENTE_MATRICULA_DUPLICADA: 'PENDENTE_MATRICULA_DUPLICADA',
  PENDENTE_DATA_PROMOCAO_INVALIDA: 'PENDENTE_DATA_PROMOCAO_INVALIDA',
  ALERTA_POSTO_DIVERGENTE: 'ALERTA_POSTO_DIVERGENTE',
  ALERTA_QUADRO_DIVERGENTE: 'ALERTA_QUADRO_DIVERGENTE',
  JA_EXISTE_REGISTRO_COMPATIVEL: 'JA_EXISTE_REGISTRO_COMPATIVEL',
  CONFLITO_REGISTRO_DIVERGENTE: 'CONFLITO_REGISTRO_DIVERGENTE',
};
const COLUNAS_ESPERADAS = ['matricula','nome_guerra','nome_completo','posto_graduacao_atual','quadro_atual','posto_graduacao_novo','quadro_novo','data_promocao','data_publicacao','ato_referencia','boletim_referencia','antiguidade_referencia_ordem','antiguidade_referencia_id','origem_dado','observacoes'];
const normalize = (v) => String(v || '').trim();
const normalizeUpper = (v) => normalize(v).toUpperCase();
const parseCsv = (t) => t.split(/\r?\n/).filter(Boolean).map((l) => l.split(',').map((c) => c.trim()));
const parseXml = (x) => new DOMParser().parseFromString(x, 'application/xml');
const getZipText = (z, p) => (z[p] ? strFromU8(z[p]) : null);
function parseXlsxRows(buf){const zip=unzipSync(new Uint8Array(buf));const wb=parseXml(getZipText(zip,'xl/workbook.xml'));const rel=parseXml(getZipText(zip,'xl/_rels/workbook.xml.rels'));const relMap=Array.from(rel.getElementsByTagName('Relationship')).reduce((a,r)=>(a[r.getAttribute('Id')]=r.getAttribute('Target'),a),{});const sstDoc=parseXml(getZipText(zip,'xl/sharedStrings.xml')||'<sst/>');const sst=Array.from(sstDoc.getElementsByTagName('si')).map((si)=>Array.from(si.getElementsByTagName('t')).map((n)=>n.textContent||'').join(''));const first=wb.getElementsByTagName('sheet')[0];const rid=first?.getAttribute('r:id');const target=relMap[rid]||'';const path=`xl/${target.replace(/^\//,'')}`;const sheet=parseXml(getZipText(zip,path));return Array.from(sheet.getElementsByTagName('row')).map((row)=>{const vals=[];Array.from(row.getElementsByTagName('c')).forEach((c)=>{const ref=c.getAttribute('r')||'';const col=((ref.match(/[A-Z]+/)||['A'])[0]).split('').reduce((i,ch)=>i*26+(ch.charCodeAt(0)-64),0)-1;const t=c.getAttribute('t');const v=c.getElementsByTagName('v')[0]?.textContent||'';vals[col]=t==='s'?(sst[Number(v)]||''):v;});return vals.map((v)=>normalize(v));});}

export async function parseArquivoPromocoes(file){const n=(file?.name||'').toLowerCase();let tabela=[];if(n.endsWith('.csv')||n.endsWith('.txt')) tabela=parseCsv(await file.text()); else if(n.endsWith('.xlsx')) tabela=parseXlsxRows(await file.arrayBuffer()); else throw new Error('Formato não suportado. Use CSV ou XLSX.');const [head,...rows]=tabela;const map=(head||[]).map((h)=>normalize(h));return rows.filter((r)=>r.some((c)=>normalize(c))).map((row,idx)=>{const out={_linha:idx+2};COLUNAS_ESPERADAS.forEach((c)=>{const i=map.indexOf(c);out[c]=normalize(i>=0?row[i]:'');});return out;});}
export function parseDate(value){const raw=normalize(value);if(!raw)return null;const iso=raw.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(iso)return iso[0];const br=raw.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(br)return `${br[3]}-${br[2]}-${br[1]}`;const d=new Date(raw);if(Number.isNaN(d.getTime()))return null;return d.toISOString().slice(0,10);} 
export function gerarPreviaImportacao(rows,militares,historicos){const mpm=militares.reduce((a,m)=>{const k=normalizeUpper(m.matricula);if(!k)return a;(a[k]||(a[k]=[])).push(m);return a;},{});const ativos=historicos.filter((h)=>normalizeUpper(h.status_registro||'ativo')==='ATIVO');const previas=rows.map((row)=>{const status=[];const matricula=normalizeUpper(row.matricula);const dataPromocao=parseDate(row.data_promocao);const matches=mpm[matricula]||[];let militar=null;if(!matricula||!matches.length)status.push(STATUS.PENDENTE_MATRICULA_NAO_ENCONTRADA);else if(matches.length>1)status.push(STATUS.PENDENTE_MATRICULA_DUPLICADA);else [militar]=matches;if(!dataPromocao)status.push(STATUS.PENDENTE_DATA_PROMOCAO_INVALIDA);if(militar&&normalizeUpper(row.posto_graduacao_atual)&&normalizeUpper(row.posto_graduacao_atual)!==normalizeUpper(militar.posto_graduacao))status.push(STATUS.ALERTA_POSTO_DIVERGENTE);if(militar&&normalizeUpper(row.quadro_atual)&&normalizeUpper(row.quadro_atual)!==normalizeUpper(militar.quadro))status.push(STATUS.ALERTA_QUADRO_DIVERGENTE);let ja=false,conf=false;if(militar&&dataPromocao){const mesmos=ativos.filter((h)=>h.militar_id===militar.id&&parseDate(h.data_promocao)===dataPromocao);ja=mesmos.some((h)=>normalizeUpper(h.posto_graduacao_novo)===normalizeUpper(row.posto_graduacao_novo));conf=mesmos.length>0&&!ja;}if(ja)status.push(STATUS.JA_EXISTE_REGISTRO_COMPATIVEL);if(conf)status.push(STATUS.CONFLITO_REGISTRO_DIVERGENTE);if(status.length===0||status.every((s)=>[STATUS.ALERTA_POSTO_DIVERGENTE,STATUS.ALERTA_QUADRO_DIVERGENTE].includes(s)))status.unshift(STATUS.OK_IMPORTAR);const bloqueante=status.some((s)=>[STATUS.PENDENTE_MATRICULA_NAO_ENCONTRADA,STATUS.PENDENTE_MATRICULA_DUPLICADA,STATUS.PENDENTE_DATA_PROMOCAO_INVALIDA,STATUS.CONFLITO_REGISTRO_DIVERGENTE,STATUS.JA_EXISTE_REGISTRO_COMPATIVEL].includes(s));return {row,militar,status,dataPromocao,podeImportar:!bloqueante&&status.includes(STATUS.OK_IMPORTAR)};});
return {previas,resumo:{totalLinhas:previas.length,militaresEncontrados:previas.filter((p)=>p.militar).length,naoEncontrados:previas.filter((p)=>p.status.includes(STATUS.PENDENTE_MATRICULA_NAO_ENCONTRADA)).length,conflitos:previas.filter((p)=>p.status.includes(STATUS.PENDENTE_MATRICULA_DUPLICADA)||p.status.includes(STATUS.CONFLITO_REGISTRO_DIVERGENTE)).length,datasInvalidas:previas.filter((p)=>p.status.includes(STATUS.PENDENTE_DATA_PROMOCAO_INVALIDA)).length,prontosImportar:previas.filter((p)=>p.podeImportar).length,registrosExistentes:previas.filter((p)=>p.status.includes(STATUS.JA_EXISTE_REGISTRO_COMPATIVEL)).length,alertasDivergencia:previas.filter((p)=>p.status.includes(STATUS.ALERTA_POSTO_DIVERGENTE)||p.status.includes(STATUS.ALERTA_QUADRO_DIVERGENTE)).length}};}
