const comunicacoesMock = [
  {
    id: '1',
    protocolo: 'CI-2026-0001',
    assunto: 'Inspeção ordinária da reserva de material',
    origem: 'Seção de Logística',
    tipo: 'Comunicado Interno',
    prioridade: 'Alta',
    status: 'Aguardando ciência',
    tags: ['logística', 'inspeção'],
    data: '2026-04-24T10:30:00.000Z',
    resumo: 'Solicita conferência documental e apresentação do inventário da reserva até 28/04.',
    conteudo: 'Solicita conferência documental e apresentação do inventário da reserva até 28/04. A inspeção ocorrerá no pátio administrativo às 09h.',
    unread: true,
    important: true,
    archived: false,
    awaitingDispatch: true,
    mailbox: 'setorial',
  },
  {
    id: '2',
    protocolo: 'CI-2026-0002',
    assunto: 'Atualização de escala de serviço',
    origem: 'Adjuntoria de Dia',
    tipo: 'Memorando',
    prioridade: 'Média',
    status: 'Em análise',
    tags: ['escala', 'serviço'],
    data: '2026-04-23T18:00:00.000Z',
    resumo: 'Nova distribuição das guarnições para o turno noturno, com vigência imediata.',
    conteudo: 'Nova distribuição das guarnições para o turno noturno, com vigência imediata. As chefias deverão confirmar recebimento até 20h.',
    unread: true,
    important: false,
    archived: false,
    awaitingDispatch: false,
    mailbox: 'pessoal',
  },
  {
    id: '3',
    protocolo: 'CI-2026-0003',
    assunto: 'Diretriz para revisão de prontuários',
    origem: 'Seção de Pessoal',
    tipo: 'Diretriz',
    prioridade: 'Baixa',
    status: 'Arquivada',
    tags: ['prontuário', 'pessoal'],
    data: '2026-04-21T14:15:00.000Z',
    resumo: 'Padroniza conferência trimestral de documentos funcionais.',
    conteudo: 'Padroniza conferência trimestral de documentos funcionais. Cada fração deverá remeter relatório consolidado para auditoria interna.',
    unread: false,
    important: false,
    archived: true,
    awaitingDispatch: false,
    mailbox: 'setorial',
  },
  {
    id: '4',
    protocolo: 'CI-2026-0004',
    assunto: 'Priorização de manutenção de viaturas',
    origem: 'Oficina Central',
    tipo: 'Ordem interna',
    prioridade: 'Alta',
    status: 'Aguardando despacho',
    tags: ['manutenção', 'viaturas'],
    data: '2026-04-22T09:45:00.000Z',
    resumo: 'Lista de viaturas com indisponibilidade crítica e ordem de priorização para reparo.',
    conteudo: 'Lista de viaturas com indisponibilidade crítica e ordem de priorização para reparo. Demanda despacho do oficial gestor para alocação de recursos.',
    unread: false,
    important: true,
    archived: false,
    awaitingDispatch: true,
    mailbox: 'pessoal',
  },
];

export const listComunicacoes = async () => {
  return Promise.resolve(comunicacoesMock);
};
