const comunicacoesMock = [
  {
    id: 'com-001',
    protocolo: 'CI-2026-0001',
    assunto: 'Escala de serviço extraordinário - Semana 18',
    origem: 'Seção de Operações',
    tipo: 'Memorando',
    prioridade: 'Alta',
    status: 'Aguardando despacho',
    tags: ['escala', 'operações'],
    data: '2026-04-24T10:30:00Z',
    resumo: 'Solicita validação da escala extraordinária prevista para a próxima semana.',
    conteudo: 'Solicita-se despacho para validação da escala de serviço extraordinário da Semana 18, com foco em reforço de efetivo no período noturno.',
    unread: true,
    important: true,
    archived: false,
    awaitingDispatch: true,
    mailbox: 'setorial',
  },
  {
    id: 'com-002',
    protocolo: 'CI-2026-0002',
    assunto: 'Atualização de inventário de equipamentos de proteção',
    origem: 'Almoxarifado Central',
    tipo: 'Comunicado',
    prioridade: 'Média',
    status: 'Em análise',
    tags: ['inventário', 'EPI'],
    data: '2026-04-23T15:00:00Z',
    resumo: 'Encaminha atualização parcial de inventário para conferência das chefias.',
    conteudo: 'Encaminhamos atualização parcial do inventário de EPIs. Favor revisar saldos e sinalizar divergências até o final do expediente.',
    unread: true,
    important: false,
    archived: false,
    awaitingDispatch: false,
    mailbox: 'pessoal',
  },
  {
    id: 'com-003',
    protocolo: 'CI-2026-0003',
    assunto: 'Diretriz de padronização documental',
    origem: 'Comando Administrativo',
    tipo: 'Diretriz',
    prioridade: 'Alta',
    status: 'Arquivada',
    tags: ['documentação', 'padronização'],
    data: '2026-04-18T09:15:00Z',
    resumo: 'Define novo padrão de formatação para comunicações internas.',
    conteudo: 'Fica instituído padrão único para formatação de comunicações internas, incluindo cabeçalho, numeração e campos obrigatórios.',
    unread: false,
    important: true,
    archived: true,
    awaitingDispatch: false,
    mailbox: 'setorial',
  },
  {
    id: 'com-004',
    protocolo: 'CI-2026-0004',
    assunto: 'Solicitação de atualização cadastral de militares',
    origem: 'Seção de Pessoal',
    tipo: 'Solicitação',
    prioridade: 'Baixa',
    status: 'Lida',
    tags: ['cadastro'],
    data: '2026-04-20T12:20:00Z',
    resumo: 'Solicita revisão dos dados cadastrais com prazo de 5 dias úteis.',
    conteudo: 'Solicitamos a atualização dos dados cadastrais dos militares vinculados ao setor, no prazo de 5 dias úteis.',
    unread: false,
    important: false,
    archived: false,
    awaitingDispatch: false,
    mailbox: 'pessoal',
  },
];

export const listarComunicacoes = async () => {
  return Promise.resolve(comunicacoesMock);
};
