import { normalizarQuadroLegado } from '../../utils/postoQuadroCompatibilidade.js';

const MATRICULA_FIELDS = ['matricula_atual', 'matricula'];
const LOTACAO_NOME_FIELDS = [
  'estrutura_nome',
  'subgrupamento_nome',
  'grupamento_nome',
  'lotacao_atual',
  'lotacao_nome',
  'lotacao',
  'subgrupamento',
  'unidade_nome',
];

function normalizarTextoCampo(value) {
  return String(value || '').trim();
}

export function getPrimeiroValorEfetivo(record = {}, fields = []) {
  for (const field of fields) {
    const value = normalizarTextoCampo(record?.[field]);
    if (value) return value;
  }

  return '';
}

export function getMatriculaEfetivo(militar = {}) {
  return getPrimeiroValorEfetivo(militar, MATRICULA_FIELDS);
}

export function getLotacaoNomeEfetivo(militar = {}) {
  return getPrimeiroValorEfetivo(militar, LOTACAO_NOME_FIELDS);
}

export function getQuadroEfetivo(militar = {}) {
  return normalizarQuadroLegado(militar?.quadro) || normalizarTextoCampo(militar?.quadro);
}

export const EXTRACAO_EFETIVO_FIELDS = Object.freeze({
  posto_graduacao: Object.freeze({
    id: 'posto_graduacao',
    label: 'Posto/graduação',
    selectable: true,
    defaultVisible: true,
    displayOrder: 10,
    category: 'Identificação',
    accessor: (militar) => normalizarTextoCampo(militar?.posto_graduacao),
    sortable: true,
    sortType: 'postoGraduacao',
    sortRank: 10,
    filterable: true,
    filterType: 'select',
    filterMode: 'backend',
    backendParam: 'postoGraduacaoFiltros',
    searchable: true,
    sourceFields: Object.freeze(['posto_graduacao']),
    cellClassName: 'font-semibold text-[#1e3a5f] whitespace-nowrap',
  }),
  nome_guerra: Object.freeze({
    id: 'nome_guerra',
    label: 'Nome de guerra',
    selectable: true,
    defaultVisible: true,
    required: true,
    displayOrder: 20,
    category: 'Identificação',
    accessor: (militar) => normalizarTextoCampo(militar?.nome_guerra),
    sortable: true,
    sortType: 'text',
    searchable: true,
    sourceFields: Object.freeze(['nome_guerra']),
    cellClassName: 'whitespace-nowrap',
  }),
  nome_completo: Object.freeze({
    id: 'nome_completo',
    label: 'Nome completo',
    selectable: true,
    defaultVisible: true,
    displayOrder: 30,
    category: 'Identificação',
    accessor: (militar) => normalizarTextoCampo(militar?.nome_completo),
    sortable: true,
    sortType: 'text',
    searchable: true,
    sourceFields: Object.freeze(['nome_completo']),
    cellClassName: 'min-w-60',
  }),
  matricula: Object.freeze({
    id: 'matricula',
    label: 'Matrícula',
    selectable: true,
    defaultVisible: true,
    required: true,
    displayOrder: 40,
    category: 'Identificação',
    accessor: getMatriculaEfetivo,
    sortable: true,
    sortType: 'naturalText',
    searchable: true,
    sourceFields: Object.freeze([...MATRICULA_FIELDS]),
    cellClassName: 'whitespace-nowrap',
  }),
  quadro: Object.freeze({
    id: 'quadro',
    label: 'Quadro',
    selectable: true,
    defaultVisible: true,
    displayOrder: 50,
    category: 'Vínculo funcional',
    accessor: getQuadroEfetivo,
    sortable: true,
    sortType: 'quadro',
    filterable: true,
    filterType: 'select',
    filterMode: 'client',
    searchable: true,
    sourceFields: Object.freeze(['quadro']),
    cellClassName: 'whitespace-nowrap',
  }),
  lotacao_nome: Object.freeze({
    id: 'lotacao_nome',
    label: 'Lotação',
    selectable: true,
    defaultVisible: true,
    displayOrder: 60,
    category: 'Vínculo funcional',
    accessor: getLotacaoNomeEfetivo,
    sortable: true,
    sortType: 'text',
    filterable: true,
    filterType: 'select',
    filterMode: 'hybrid',
    backendParam: 'lotacaoFiltro',
    searchable: true,
    sourceFields: Object.freeze([...LOTACAO_NOME_FIELDS]),
    cellClassName: 'min-w-56',
  }),
  status_cadastro: Object.freeze({
    id: 'status_cadastro',
    label: 'Status',
    selectable: true,
    defaultVisible: true,
    displayOrder: 70,
    category: 'Vínculo funcional',
    accessor: (militar) => normalizarTextoCampo(militar?.status_cadastro),
    sortable: true,
    sortType: 'statusCadastro',
    sortRank: 20,
    filterable: true,
    filterType: 'select',
    filterMode: 'backend',
    backendParam: 'statusCadastro',
    searchable: true,
    sourceFields: Object.freeze(['status_cadastro']),
    cellClassName: 'whitespace-nowrap',
    renderAs: 'statusBadge',
  }),
  situacao_militar: Object.freeze({
    id: 'situacao_militar',
    label: 'Situação militar',
    selectable: true,
    defaultVisible: true,
    displayOrder: 80,
    category: 'Vínculo funcional',
    accessor: (militar) => normalizarTextoCampo(militar?.situacao_militar),
    sortable: true,
    sortType: 'text',
    filterable: true,
    filterType: 'select',
    filterMode: 'backend',
    backendParam: 'situacaoMilitar',
    searchable: true,
    sourceFields: Object.freeze(['situacao_militar']),
    cellClassName: 'whitespace-nowrap',
  }),
  funcao: Object.freeze({
    id: 'funcao',
    label: 'Função',
    selectable: true,
    defaultVisible: true,
    displayOrder: 90,
    category: 'Vínculo funcional',
    accessor: (militar) => normalizarTextoCampo(militar?.funcao),
    sortable: true,
    sortType: 'text',
    filterable: true,
    filterType: 'select',
    filterMode: 'client',
    searchable: true,
    sourceFields: Object.freeze(['funcao']),
    cellClassName: 'min-w-44',
  }),
  condicao: Object.freeze({
    id: 'condicao',
    label: 'Condição',
    selectable: true,
    defaultVisible: false,
    displayOrder: 100,
    category: 'Vínculo funcional',
    accessor: (militar) => normalizarTextoCampo(militar?.condicao),
    sortable: true,
    sortType: 'text',
    filterable: true,
    filterType: 'select',
    filterMode: 'client',
    searchable: true,
    sourceFields: Object.freeze(['condicao']),
  }),

  ferias_tem_no_periodo: Object.freeze({
    id: 'ferias_tem_no_periodo',
    label: 'Férias no período?',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 210,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_tem_no_periodo),
    sortable: true,
    sortType: 'text',
    filterable: true,
    filterType: 'select',
    filterMode: 'client',
    sourceFields: Object.freeze(['ferias_tem_no_periodo']),
    cellClassName: 'whitespace-nowrap',
  }),
  ferias_em_curso: Object.freeze({
    id: 'ferias_em_curso',
    label: 'Férias em curso?',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 220,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_em_curso),
    sortable: true,
    sortType: 'text',
    filterable: true,
    filterType: 'select',
    filterMode: 'client',
    sourceFields: Object.freeze(['ferias_em_curso']),
    cellClassName: 'whitespace-nowrap',
  }),
  ferias_status_resumido: Object.freeze({
    id: 'ferias_status_resumido',
    label: 'Status férias',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 230,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_status_resumido),
    sortable: true,
    sortType: 'text',
    filterable: true,
    filterType: 'select',
    filterMode: 'client',
    sourceFields: Object.freeze(['ferias_status_resumido']),
    cellClassName: 'min-w-44',
  }),
  ferias_proxima_data_inicio: Object.freeze({
    id: 'ferias_proxima_data_inicio',
    label: 'Próx. férias início',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 240,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_proxima_data_inicio),
    sortable: true,
    sortType: 'naturalText',
    sourceFields: Object.freeze(['ferias_proxima_data_inicio']),
    cellClassName: 'whitespace-nowrap',
  }),
  ferias_proxima_data_fim: Object.freeze({
    id: 'ferias_proxima_data_fim',
    label: 'Próx. férias fim',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 250,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_proxima_data_fim),
    sortable: true,
    sortType: 'naturalText',
    sourceFields: Object.freeze(['ferias_proxima_data_fim']),
    cellClassName: 'whitespace-nowrap',
  }),
  ferias_proxima_data_retorno: Object.freeze({
    id: 'ferias_proxima_data_retorno',
    label: 'Próx. férias retorno',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 260,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_proxima_data_retorno),
    sortable: true,
    sortType: 'naturalText',
    sourceFields: Object.freeze(['ferias_proxima_data_retorno']),
    cellClassName: 'whitespace-nowrap',
  }),
  ferias_total_registros_periodo: Object.freeze({
    id: 'ferias_total_registros_periodo',
    label: 'Férias registros período',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 270,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_total_registros_periodo),
    sortable: true,
    sortType: 'naturalText',
    sourceFields: Object.freeze(['ferias_total_registros_periodo']),
    cellClassName: 'whitespace-nowrap text-right',
  }),
  ferias_total_dias_periodo: Object.freeze({
    id: 'ferias_total_dias_periodo',
    label: 'Férias dias período',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 280,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_total_dias_periodo),
    sortable: true,
    sortType: 'naturalText',
    sourceFields: Object.freeze(['ferias_total_dias_periodo']),
    cellClassName: 'whitespace-nowrap text-right',
  }),
  ferias_tipo_proxima: Object.freeze({
    id: 'ferias_tipo_proxima',
    label: 'Tipo próx. férias',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 290,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_tipo_proxima),
    sortable: true,
    sortType: 'text',
    sourceFields: Object.freeze(['ferias_tipo_proxima']),
  }),
  ferias_periodo_aquisitivo_ref: Object.freeze({
    id: 'ferias_periodo_aquisitivo_ref',
    label: 'Período aquisitivo férias',
    selectable: true,
    defaultVisible: false,
    exportable: false,
    displayOrder: 300,
    category: 'Férias (cruzamento relacionado)',
    accessor: (militar) => normalizarTextoCampo(militar?.ferias_periodo_aquisitivo_ref),
    sortable: true,
    sortType: 'naturalText',
    sourceFields: Object.freeze(['ferias_periodo_aquisitivo_ref']),
    cellClassName: 'whitespace-nowrap',
  }),
});

export const EXTRACAO_EFETIVO_DEFAULT_COLUMNS = Object.freeze([
  EXTRACAO_EFETIVO_FIELDS.posto_graduacao,
  EXTRACAO_EFETIVO_FIELDS.nome_guerra,
  EXTRACAO_EFETIVO_FIELDS.nome_completo,
  EXTRACAO_EFETIVO_FIELDS.matricula,
  EXTRACAO_EFETIVO_FIELDS.quadro,
  EXTRACAO_EFETIVO_FIELDS.lotacao_nome,
  EXTRACAO_EFETIVO_FIELDS.status_cadastro,
  EXTRACAO_EFETIVO_FIELDS.situacao_militar,
  EXTRACAO_EFETIVO_FIELDS.funcao,
]);

export const EXTRACAO_EFETIVO_FORBIDDEN_FIELDS = Object.freeze([
  'religiao',
  'tipo_sanguineo',
  'sexo',
  'etnia',
  'data_nascimento',
  'cpf',
  'rg',
  'cnh',
  'filiacao',
  'endereco',
  'telefone',
  'email_particular',
  'email_funcional',
  'dados_bancarios',
  'altura',
  'peso',
  'foto',
  'dados_medicos',
  'saude',
]);

export function getValorCampoEfetivo(militar = {}, fieldId = '') {
  const field = EXTRACAO_EFETIVO_FIELDS[fieldId];

  if (!field) return '';

  return field.accessor(militar);
}
