import React from 'react';
import { CheckCircle2, Loader2, UserPlus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import CoberturaPeriodoChips from '@/components/ferias/CoberturaPeriodoChips';

export default function CoberturaPlanoFerias({ loading, militares, selecionados, onToggle, onToggleTodos, onCriar }) {
  if (loading) return <div className="flex items-center justify-center gap-2 py-16 text-sm text-slate-500"><Loader2 className="h-5 w-5 animate-spin" />Calculando cobertura do plano...</div>;
  if (!militares.length) return <div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-10 text-center"><CheckCircle2 className="mx-auto h-9 w-9 text-emerald-600" /><h3 className="mt-3 font-black text-emerald-900">Cobertura completa no seu escopo</h3><p className="mt-1 text-sm text-emerald-700">Todos os militares elegíveis já estão incluídos em alguma campanha deste plano.</p></div>;
  const todos = militares.every((m) => selecionados.includes(m.militar_id));
  return <><div className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs text-slate-600"><tr><th className="w-12 px-4 py-3"><input aria-label="Selecionar todos os militares não cobertos" type="checkbox" checked={todos} onChange={onToggleTodos} /></th><th className="px-4 py-3 text-left font-bold">Militar</th><th className="px-4 py-3 text-left font-bold">Lotação</th><th className="px-4 py-3 text-left font-bold">Períodos elegíveis</th></tr></thead><tbody className="divide-y divide-slate-100">{militares.map((militar) => <tr key={militar.militar_id} className="hover:bg-blue-50/40"><td className="px-4 py-3"><input aria-label={`Selecionar ${militar.militar_nome}`} type="checkbox" checked={selecionados.includes(militar.militar_id)} onChange={() => onToggle(militar.militar_id)} /></td><td className="px-4 py-3"><div className="font-bold text-slate-900">{militar.militar_nome}</div><div className="mt-0.5 text-xs text-slate-500">{militar.militar_posto || '-'} · {militar.militar_matricula || 'sem matrícula'}</div></td><td className="px-4 py-3 text-slate-600">{militar.lotacao_nome}</td><td className="px-4 py-3"><CoberturaPeriodoChips periodos={militar.periodos_elegiveis} /></td></tr>)}</tbody></table></div></div>{selecionados.length > 0 && <div className="sticky bottom-4 z-20 mx-auto mt-4 flex max-w-xl items-center justify-between gap-3 rounded-2xl border border-blue-200 bg-white p-3 shadow-xl"><span className="text-sm font-bold text-slate-700">{selecionados.length} selecionado(s)</span><Button onClick={onCriar} className="bg-blue-700 hover:bg-blue-800"><UserPlus className="h-4 w-4" />Criar campanha com selecionados</Button></div>}</>;
}