import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
const OPERACOES = new Set(['create', 'update', 'delete']);
const ACOES_PERMITIDAS = new Set(['gerir_estrutura_organizacional', 'gerir_estrutura']);
const CAMPOS_USUARIO_ACESSO = ['id', 'user_email', 'ativo', 'tipo_acesso', 'perfil_id'];
const normalizeTipo = (t: unknown) => String(t || '').trim().toLowerCase();
const normalizeEmail = (e: unknown) => String(e || '').trim().toLowerCase();
const erro = (status: number, message: string) => Response.json({ error: message }, { status });
function extrairMatrizPermissoes(descricao: unknown) { if (typeof descricao !== 'string' || !descricao) return {}; const s = descricao.indexOf('[SGP_PERMISSIONS_MATRIX]'); const e = descricao.indexOf('[/SGP_PERMISSIONS_MATRIX]'); if (s === -1 || e === -1 || e <= s) return {}; try { return JSON.parse(descricao.slice(s + '[SGP_PERMISSIONS_MATRIX]'.length, e).trim()) || {}; } catch { return {}; } }
function consolidarActions(perfis: any[], acessos: any[]) { const actions: Record<string, boolean> = {}; const apply = (src: any) => Object.entries(src || {}).forEach(([k, v]) => { if (!k.startsWith('perm_') || typeof v !== 'boolean') return; const key = k.replace(/^perm_/, ''); if (v === true) actions[key] = true; else if (!(key in actions)) actions[key] = false; }); (perfis || []).forEach((p) => { apply(p); apply(extrairMatrizPermissoes(p?.descricao)); }); (acessos || []).forEach(apply); return actions; }
async function resolverPermissoes(base44: any, email: string) { const acessos = await base44.asServiceRole.entities.UsuarioAcesso.filter({ user_email: email, ativo: true }, undefined, 100, 0, CAMPOS_USUARIO_ACESSO); const isAdminByAccess = (acessos || []).some((a: any) => normalizeTipo(a.tipo_acesso) === 'admin'); const perfilIds = Array.from(new Set((acessos || []).map((a: any) => a?.perfil_id).filter(Boolean))); const perfis = perfilIds.length > 0 ? await base44.asServiceRole.entities.PerfilPermissao.filter({ id: { $in: perfilIds }, ativo: true }) : []; return { actions: consolidarActions(perfis || [], acessos || []), isAdminByAccess }; }
function validarPayload(operation: string, registroId: string | undefined, data: Record<string, unknown> | undefined) { if (!OPERACOES.has(operation)) throw new Error('Operação inválida. Use create, update ou delete.'); if ((operation === 'update' || operation === 'delete') && !registroId) throw new Error('registroId é obrigatório para update/delete.'); if ((operation === 'create' || operation === 'update') && (!data || typeof data !== 'object')) throw new Error('data é obrigatória para create/update.'); if ((operation === 'create' || operation === 'update') && !String(data?.nome || '').trim()) throw new Error('nome é obrigatório para create/update.'); if (operation === 'create' || operation === 'update') { const tipo = String(data?.tipo || '').trim(); const nivel = Number(data?.nivel_hierarquico); const parent = String(data?.grupamento_id || data?.setor_pai_id || data?.parent_id || '').trim(); if (!tipo) throw new Error('tipo é obrigatório.'); if (![1, 2, 3].includes(nivel)) throw new Error('nivel_hierarquico inválido.'); if (nivel === 1 && parent) throw new Error('Setor (nível 1) não pode ter unidade pai.'); if (nivel > 1 && !parent) throw new Error('Subsetor/Unidade devem possuir unidade pai.'); } }
Deno.serve(async (req) => { try { const base44 = createClientFromRequest(req); const body = await req.json().catch(() => ({})); const operation = String(body?.operation || '').trim(); const registroId = body?.registroId ? String(body.registroId) : undefined; const data = (body?.data && typeof body.data === 'object') ? body.data : undefined; validarPayload(operation, registroId, data as any); const user = await base44.auth.me(); const email = normalizeEmail(user?.email); if (!email) return erro(401, 'Usuário não autenticado.'); const { actions, isAdminByAccess } = await resolverPermissoes(base44, email); const autorizado = isAdminByAccess || Array.from(ACOES_PERMITIDAS).some((acao) => actions?.[acao] === true); if (!autorizado) return erro(403, 'Sem permissão para gerir estrutura organizacional.'); if (operation === 'create') return Response.json({ ok: true, data: await base44.asServiceRole.entities.Subgrupamento.create(data) }); if (operation === 'update') return Response.json({ ok: true, data: await base44.asServiceRole.entities.Subgrupamento.update(registroId, data) }); const id = String(registroId); const filhos = await base44.asServiceRole.entities.Subgrupamento.filter({ parent_id: id }, undefined, 1, 0, ['id']); if ((filhos || []).length > 0) return erro(409, 'Não é possível excluir: existem unidades filhas vinculadas.'); for (const filtro of [{ estrutura_id: id }, { subgrupamento_id: id }, { grupamento_id: id }]) { const vinculados = await base44.asServiceRole.entities.Militar.filter(filtro, undefined, 1, 0, ['id']); if ((vinculados || []).length > 0) return erro(409, 'Não é possível excluir: existem militares vinculados a esta estrutura.'); } return Response.json({ ok: true, data: await base44.asServiceRole.entities.Subgrupamento.delete(id) }); } catch (err: any) { const message = err?.message || 'Erro inesperado no CUD da Estrutura Organizacional.'; const status = Number(err?.status || err?.response?.status || 500); return erro(Number.isFinite(status) ? status : 500, message); } });
