export const ENTITY_ACTION_RULES = {
  'UsuarioAcesso.create': 'perm_gerir_permissoes',
  'UsuarioAcesso.update': 'perm_gerir_permissoes',
  'UsuarioAcesso.delete': 'perm_gerir_permissoes',
  'PerfilPermissao.create': 'perm_gerir_permissoes',
  'PerfilPermissao.update': 'perm_gerir_permissoes',
  'PerfilPermissao.delete': 'perm_gerir_permissoes',
  'Ferias.delete': 'perm_excluir_ferias',
  'Ferias.reconcile': 'perm_gerir_cadeia_ferias',
  'Ferias.recalculate': 'perm_recalcular_ferias',
  'Atestado.delete': 'perm_excluir_atestado',
  'JISO.updateDecision': 'perm_registrar_decisao_jiso',
  'QuadroOperacional.update': 'perm_gerir_quadro',
  'CardOperacional.move': 'perm_mover_card',
  'ColunaOperacional.reorder': 'perm_gerir_colunas',
  'CardOperacional.archive': 'perm_arquivar_card',
  'CardChecklistItem.create': 'perm_gerir_acoes_operacionais',
  'CardChecklistItem.update': 'perm_gerir_acoes_operacionais',
};
