export const ENTITY_SCOPE_REGISTRY = {
  Militar: 'direct',
  Subgrupamento: 'direct',
  Ferias: 'byMilitar',
  PeriodoAquisitivo: 'byMilitar',
  RegistroLivro: 'byMilitar',
  PublicacaoExOfficio: 'byMilitar',
  Atestado: 'byMilitar',
  JISO: 'byMilitar',
  SolicitacaoAtualizacao: 'byMilitar',
  HistoricoComportamento: 'byMilitar',
  UsuarioAcesso: 'adminOnly',
  PerfilPermissao: 'adminOnly',
  TemplateTexto: 'adminOnly',
  QuadroOperacional: 'quadro',
  ColunaOperacional: 'quadro',
  CardOperacional: 'quadro',
  CardChecklistItem: 'quadro',
  CardComentario: 'quadro',
  CardVinculo: 'quadro',
};
