export const ENTITY_MODULE_REGISTRY = {
  Militar: 'militares',
  Ferias: 'ferias',
  PeriodoAquisitivo: 'ferias',
  RegistroLivro: 'livro',
  PublicacaoExOfficio: 'publicacoes',
  Atestado: 'atestados',
  JISO: 'atestados',
  UsuarioAcesso: 'configuracoes',
  PerfilPermissao: 'configuracoes',
  SolicitacaoAtualizacao: 'militares',
  QuadroOperacional: 'quadro_operacional',
  ColunaOperacional: 'quadro_operacional',
  CardOperacional: 'quadro_operacional',
  CardChecklistItem: 'quadro_operacional',
  CardComentario: 'quadro_operacional',
  CardVinculo: 'quadro_operacional',
  Subgrupamento: 'configuracoes',
  TemplateTexto: 'templates',
  HistoricoComportamento: 'militares',
};
